# Generated by Django 2.1 on 2018-08-23 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_fruit_vegetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fruit',
            options={},
        ),
        migrations.RemoveField(
            model_name='fruit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fruit',
            name='image',
        ),
        migrations.AddField(
            model_name='fruit',
            name='fruit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vegetable',
        ),
    ]
